examples: Require correct file paths
When running the examples from the repository root like `php examples/example_atom.php`,
the scripts will complain and eventually fail:

    Warning: include(../Item.php): Failed to open stream: No such file or directory
    Fatal error: Uncaught Error: Class "FeedWriter\ATOM" not found

Let’s replace the `include`s with `require_once`s to fail eagerly on missing library
and use absolute path through the `__DIR__` constant introduced in PHP 5.3
instead of relying on lookup paths.